blank_issues_enabled: false
contact_links:
  - name: Bug Report
    about: Report a bug or issue with the modpack.
  - name: Mod Request
    about: Suggest a new mod, update, or change to the modpack.
  - name: Mod Removal or Replacemnt
    about: Suggest a mod to be removed and/or replaced in the modpack.
  - name: Setting Change
    about: Suggest a change to the modpack's settings or configurations.
  - name: General Question
    about: Ask questions or seek clarification about the modpack.
