blank_issues_enabled: false
contact_links:
  - name: Mod Suggestion
    url: https://github.com/DeadLector/TchicX-Modpack/issues/new?template=mod_suggestion.md
    about: Suggest a new mod, update, or change to the modpack
  - name: Bug Report
    url: https://github.com/DeadLector/TchicX-Modpack/issues/new?template=bug_report.md
    about: Report a bug or issue with the modpack
  - name: Other
    url: https://github.com/DeadLector/TchicX-Modpack/issues/new
    about: For any other inquiries or suggestions
